name: dotnet-statiq-beckshome-blog
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build image
  jobs:

  - job: Transform
    displayName: Transform markdown content to Statiq output
    variables:
      project: "statiq-site.csproj"
    steps:
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: "build"
        projects: $(project)

    - task: DotNetCoreCLI@2
      displayName: Generate
      inputs:
        command: "run"
        projects: $(project)