name: dotnet-statiq-beckshome-blog
trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  ARTIFACT_NAME: BeckshomeBlog

stages:
- stage: Build
  displayName: Build image
  jobs:

  - job: Transform
    displayName: Transform markdown content to Statiq output
    variables:
      project: "statiq-site.csproj"
    steps:
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: "build"
        projects: $(project)

    - task: DotNetCoreCLI@2
      displayName: Generate
      inputs:
        command: "run"
        projects: $(project)
        
    - task: CopyFiles@2
      displayName: Copy
      inputs:
        SourceFolder: "$(Build.SourcesDirectory)/output"
        Contents: "**"
        TargetFolder: "$(Build.ArtifactStagingDirectory)/output"
        
    - task: PublishPipelineArtifact@1
      displayName: Share
      inputs:
        targetPath: "$(Build.ArtifactStagingDirectory)/output"
        artifact: "$(ARTIFACT_NAME)"
        publishLocation: "pipeline"
      
  stage: Release
  displayName: Deploy static content to Azure
  jobs:
  - deployment: DeployToStorage
    displayName: Deploy to Azure Storage
    environment: developmomentum-production

    variables:
      AZURE_STORAGE_ACCOUNT: beckshomestorage

    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureFileCopy@4
              displayName: 'Copy Files to Storage'
              inputs:
                azureSubscription: 'beckshome-static'
                SourcePath: '$(Pipeline.Workspace)/$(ARTIFACT_NAME)/*'
                Destination: 'AzureBlob'
                storage: '$(AZURE_STORAGE_ACCOUNT)'
                ContainerName: '$web'