name: dotnet-statiq-beckshome-blog
trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  ARTIFACT_NAME: BeckshomeBlog

stages:
- stage: Build
  displayName: Build image
  jobs:

  - job: Transform
    displayName: Transform markdown content to Statiq output
    variables:
      project: "statiq-site.csproj"
    steps:
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: "build"
        projects: $(project)

    - task: DotNetCoreCLI@2
      displayName: Generate
      inputs:
        command: "run"
        projects: $(project)
        
    - task: CopyFiles@2
      displayName: Copy
      inputs:
        SourceFolder: "$(Build.SourcesDirectory)/output"
        Contents: "**"
        TargetFolder: "$(Build.ArtifactStagingDirectory)/output"
        
    - task: PublishPipelineArtifact@1
      displayName: Share
      inputs:
        targetPath: "$(Build.ArtifactStagingDirectory)/output"
        artifact: "$(ARTIFACT_NAME)"
        publishLocation: "pipeline"
      
- stage: Release
  displayName: Deploy static content to Azure
  jobs:
  - deployment: DeployToStorage
    displayName: Deploy to Azure Storage
    environment: developmomentum-production

    variables:
      AZURE_STORAGE_ACCOUNT: beckshomestorage

    strategy:
      runOnce:
        deploy:
          steps:
          
            - task: AzureCLI@2
              displayName: 'Delete Existing Files'
              inputs:
                azureSubscription: 'beckshome-static'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: 'az storage blob delete-batch -s `$web --account-name $(AZURE_STORAGE_ACCOUNT)'
            - task: AzureCLI@2
              displayName: 'Copy Files to Storage'
              inputs:
                azureSubscription: 'beckshome-static'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: 'az storage blob upload-batch -d `$web --account-name $(AZURE_STORAGE_ACCOUNT) -s "$(Pipeline.Workspace)/$(ARTIFACT_NAME)/"'